#!/bin/bash

# fail fast on errors
set -e

# normalise to fill path
work_dir=$(cd $(dirname $0)/.. ; pwd)
app_dir=${1:=/app}

[[ ${work_dir} != ${app_dir} ]] && PLATFORM="drie" || PLATFORM="heroku"
export PLATFORM
echo "platform detected as ${PLATFORM}"

shopt -s nullglob
for hook_path in ${work_dir}/lib/hooks/*.hook ; do
  hook=$(basename $hook_path)
  echo "running $(basename $hook)"
  source ${work_dir}/lib/hooks/${hook} ${work_dir} ${app_dir}
done
