#!/bin/bash

# fail fast on errors
set -e

# normalise to fill path
work_dir=$(cd $(dirname $0)/.. ; pwd)
app_dir=${1:=/app}

if [[ -z ${PLATFORM+x} && ${work_dir} != ${app_dir} ]] ; then
  export PLATFORM="drie"
elif [[ -z ${PLATFORM+x} ]] ; then
  export PLATFORM="heroku"
fi

echo "platform detected as ${PLATFORM}"

shopt -s nullglob
for hook_path in ${work_dir}/lib/hooks/*.hook ; do
  hook=$(basename $hook_path)
  echo "running $(basename $hook)"
  source ${work_dir}/lib/hooks/${hook} ${work_dir} ${app_dir}
done
